/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AddonsRouteImport } from './routes/addons'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SpecialistsRouteImport } from './routes/specialists'
import { Route as VerifyDeviceRouteImport } from './routes/verify-device'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedAdminAddonsRouteImport } from './routes/_authenticated/admin.addons'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedAdminDeliveryRouteImport } from './routes/_authenticated/admin.delivery'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin.sales'
import { Route as AuthenticatedStatementMonthRouteImport } from './routes/_authenticated/statement.$month'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as AuthenticatedAdminClientsBusinessIdRouteImport } from './routes/_authenticated/admin.clients.$businessId'
import { Route as ApiPublicCronApplyPlanChangesRouteImport } from './routes/api/public/cron/apply-plan-changes'
import { Route as ApiPublicCronBookingRemindersRouteImport } from './routes/api/public/cron/booking-reminders'
import { Route as ApiPublicCronExpireBusinessesRouteImport } from './routes/api/public/cron/expire-businesses'
import { Route as ApiPublicCronMonthlyStatementsRouteImport } from './routes/api/public/cron/monthly-statements'
import { Route as ApiPublicCronReviewRequestsRouteImport } from './routes/api/public/cron/review-requests'
import { Route as ApiPublicDeviceStartRouteImport } from './routes/api/public/device/start'
import { Route as ApiPublicDeviceVerifyRouteImport } from './routes/api/public/device/verify'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsRoute = AddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsRoute = SpecialistsRouteImport.update({
  id: '/specialists',
  path: '/specialists',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyDeviceRoute = VerifyDeviceRouteImport.update({
  id: '/verify-device',
  path: '/verify-device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAddonsRoute =
  AuthenticatedAdminAddonsRouteImport.update({
    id: '/addons',
    path: '/addons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDeliveryRoute =
  AuthenticatedAdminDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStatementMonthRoute =
  AuthenticatedStatementMonthRouteImport.update({
    id: '/statement/$month',
    path: '/statement/$month',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsBusinessIdRoute =
  AuthenticatedAdminClientsBusinessIdRouteImport.update({
    id: '/clients/$businessId',
    path: '/clients/$businessId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCronApplyPlanChangesRoute =
  ApiPublicCronApplyPlanChangesRouteImport.update({
    id: '/api/public/cron/apply-plan-changes',
    path: '/api/public/cron/apply-plan-changes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBookingRemindersRoute =
  ApiPublicCronBookingRemindersRouteImport.update({
    id: '/api/public/cron/booking-reminders',
    path: '/api/public/cron/booking-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronExpireBusinessesRoute =
  ApiPublicCronExpireBusinessesRouteImport.update({
    id: '/api/public/cron/expire-businesses',
    path: '/api/public/cron/expire-businesses',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMonthlyStatementsRoute =
  ApiPublicCronMonthlyStatementsRouteImport.update({
    id: '/api/public/cron/monthly-statements',
    path: '/api/public/cron/monthly-statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReviewRequestsRoute =
  ApiPublicCronReviewRequestsRouteImport.update({
    id: '/api/public/cron/review-requests',
    path: '/api/public/cron/review-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeviceStartRoute = ApiPublicDeviceStartRouteImport.update({
  id: '/api/public/device/start',
  path: '/api/public/device/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceVerifyRoute = ApiPublicDeviceVerifyRouteImport.update({
  id: '/api/public/device/verify',
  path: '/api/public/device/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/proof': typeof ProofRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialists': typeof SpecialistsRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/admin/addons': typeof AuthenticatedAdminAddonsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/statement/$month': typeof AuthenticatedStatementMonthRoute
  '/admin/clients/$businessId': typeof AuthenticatedAdminClientsBusinessIdRoute
  '/api/public/cron/apply-plan-changes': typeof ApiPublicCronApplyPlanChangesRoute
  '/api/public/cron/booking-reminders': typeof ApiPublicCronBookingRemindersRoute
  '/api/public/cron/expire-businesses': typeof ApiPublicCronExpireBusinessesRoute
  '/api/public/cron/monthly-statements': typeof ApiPublicCronMonthlyStatementsRoute
  '/api/public/cron/review-requests': typeof ApiPublicCronReviewRequestsRoute
  '/api/public/device/start': typeof ApiPublicDeviceStartRoute
  '/api/public/device/verify': typeof ApiPublicDeviceVerifyRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/proof': typeof ProofRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialists': typeof SpecialistsRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/admin/addons': typeof AuthenticatedAdminAddonsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/statement/$month': typeof AuthenticatedStatementMonthRoute
  '/admin/clients/$businessId': typeof AuthenticatedAdminClientsBusinessIdRoute
  '/api/public/cron/apply-plan-changes': typeof ApiPublicCronApplyPlanChangesRoute
  '/api/public/cron/booking-reminders': typeof ApiPublicCronBookingRemindersRoute
  '/api/public/cron/expire-businesses': typeof ApiPublicCronExpireBusinessesRoute
  '/api/public/cron/monthly-statements': typeof ApiPublicCronMonthlyStatementsRoute
  '/api/public/cron/review-requests': typeof ApiPublicCronReviewRequestsRoute
  '/api/public/device/start': typeof ApiPublicDeviceStartRoute
  '/api/public/device/verify': typeof ApiPublicDeviceVerifyRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/addons': typeof AddonsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/proof': typeof ProofRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialists': typeof SpecialistsRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/admin/addons': typeof AuthenticatedAdminAddonsRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/statement/$month': typeof AuthenticatedStatementMonthRoute
  '/_authenticated/admin/clients/$businessId': typeof AuthenticatedAdminClientsBusinessIdRoute
  '/api/public/cron/apply-plan-changes': typeof ApiPublicCronApplyPlanChangesRoute
  '/api/public/cron/booking-reminders': typeof ApiPublicCronBookingRemindersRoute
  '/api/public/cron/expire-businesses': typeof ApiPublicCronExpireBusinessesRoute
  '/api/public/cron/monthly-statements': typeof ApiPublicCronMonthlyStatementsRoute
  '/api/public/cron/review-requests': typeof ApiPublicCronReviewRequestsRoute
  '/api/public/device/start': typeof ApiPublicDeviceStartRoute
  '/api/public/device/verify': typeof ApiPublicDeviceVerifyRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addons'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/platform'
    | '/portal'
    | '/pricing'
    | '/proof'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/specialists'
    | '/verify-device'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/bookings'
    | '/business'
    | '/catalog'
    | '/customers'
    | '/dashboard'
    | '/onboarding'
    | '/referrals'
    | '/team'
    | '/admin/addons'
    | '/admin/calendar'
    | '/admin/delivery'
    | '/admin/documents'
    | '/admin/invites'
    | '/admin/sales'
    | '/statement/$month'
    | '/admin/clients/$businessId'
    | '/api/public/cron/apply-plan-changes'
    | '/api/public/cron/booking-reminders'
    | '/api/public/cron/expire-businesses'
    | '/api/public/cron/monthly-statements'
    | '/api/public/cron/review-requests'
    | '/api/public/device/start'
    | '/api/public/device/verify'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/transactional/preview'
    | '/admin/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addons'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/platform'
    | '/portal'
    | '/pricing'
    | '/proof'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/specialists'
    | '/verify-device'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/bookings'
    | '/business'
    | '/catalog'
    | '/customers'
    | '/dashboard'
    | '/onboarding'
    | '/referrals'
    | '/team'
    | '/admin/addons'
    | '/admin/calendar'
    | '/admin/delivery'
    | '/admin/documents'
    | '/admin/invites'
    | '/admin/sales'
    | '/statement/$month'
    | '/admin/clients/$businessId'
    | '/api/public/cron/apply-plan-changes'
    | '/api/public/cron/booking-reminders'
    | '/api/public/cron/expire-businesses'
    | '/api/public/cron/monthly-statements'
    | '/api/public/cron/review-requests'
    | '/api/public/device/start'
    | '/api/public/device/verify'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/transactional/preview'
    | '/admin/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/addons'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/platform'
    | '/portal'
    | '/pricing'
    | '/proof'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/specialists'
    | '/verify-device'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/bookings'
    | '/_authenticated/business'
    | '/_authenticated/catalog'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/referrals'
    | '/_authenticated/team'
    | '/_authenticated/admin/addons'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/delivery'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/invites'
    | '/_authenticated/admin/sales'
    | '/_authenticated/statement/$month'
    | '/_authenticated/admin/clients/$businessId'
    | '/api/public/cron/apply-plan-changes'
    | '/api/public/cron/booking-reminders'
    | '/api/public/cron/expire-businesses'
    | '/api/public/cron/monthly-statements'
    | '/api/public/cron/review-requests'
    | '/api/public/device/start'
    | '/api/public/device/verify'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/admin/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AddonsRoute: typeof AddonsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PlatformRoute: typeof PlatformRoute
  PortalRoute: typeof PortalRoute
  PricingRoute: typeof PricingRoute
  ProofRoute: typeof ProofRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialistsRoute: typeof SpecialistsRoute
  VerifyDeviceRoute: typeof VerifyDeviceRoute
  ApiPublicCronApplyPlanChangesRoute: typeof ApiPublicCronApplyPlanChangesRoute
  ApiPublicCronBookingRemindersRoute: typeof ApiPublicCronBookingRemindersRoute
  ApiPublicCronExpireBusinessesRoute: typeof ApiPublicCronExpireBusinessesRoute
  ApiPublicCronMonthlyStatementsRoute: typeof ApiPublicCronMonthlyStatementsRoute
  ApiPublicCronReviewRequestsRoute: typeof ApiPublicCronReviewRequestsRoute
  ApiPublicDeviceStartRoute: typeof ApiPublicDeviceStartRoute
  ApiPublicDeviceVerifyRoute: typeof ApiPublicDeviceVerifyRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons': {
      id: '/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists': {
      id: '/specialists'
      path: '/specialists'
      fullPath: '/specialists'
      preLoaderRoute: typeof SpecialistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-device': {
      id: '/verify-device'
      path: '/verify-device'
      fullPath: '/verify-device'
      preLoaderRoute: typeof VerifyDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/addons': {
      id: '/_authenticated/admin/addons'
      path: '/addons'
      fullPath: '/admin/addons'
      preLoaderRoute: typeof AuthenticatedAdminAddonsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/delivery': {
      id: '/_authenticated/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthenticatedAdminDeliveryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/statement/$month': {
      id: '/_authenticated/statement/$month'
      path: '/statement/$month'
      fullPath: '/statement/$month'
      preLoaderRoute: typeof AuthenticatedStatementMonthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/$businessId': {
      id: '/_authenticated/admin/clients/$businessId'
      path: '/clients/$businessId'
      fullPath: '/admin/clients/$businessId'
      preLoaderRoute: typeof AuthenticatedAdminClientsBusinessIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cron/apply-plan-changes': {
      id: '/api/public/cron/apply-plan-changes'
      path: '/api/public/cron/apply-plan-changes'
      fullPath: '/api/public/cron/apply-plan-changes'
      preLoaderRoute: typeof ApiPublicCronApplyPlanChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/booking-reminders': {
      id: '/api/public/cron/booking-reminders'
      path: '/api/public/cron/booking-reminders'
      fullPath: '/api/public/cron/booking-reminders'
      preLoaderRoute: typeof ApiPublicCronBookingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expire-businesses': {
      id: '/api/public/cron/expire-businesses'
      path: '/api/public/cron/expire-businesses'
      fullPath: '/api/public/cron/expire-businesses'
      preLoaderRoute: typeof ApiPublicCronExpireBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/monthly-statements': {
      id: '/api/public/cron/monthly-statements'
      path: '/api/public/cron/monthly-statements'
      fullPath: '/api/public/cron/monthly-statements'
      preLoaderRoute: typeof ApiPublicCronMonthlyStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/review-requests': {
      id: '/api/public/cron/review-requests'
      path: '/api/public/cron/review-requests'
      fullPath: '/api/public/cron/review-requests'
      preLoaderRoute: typeof ApiPublicCronReviewRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/start': {
      id: '/api/public/device/start'
      path: '/api/public/device/start'
      fullPath: '/api/public/device/start'
      preLoaderRoute: typeof ApiPublicDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/verify': {
      id: '/api/public/device/verify'
      path: '/api/public/device/verify'
      fullPath: '/api/public/device/verify'
      preLoaderRoute: typeof ApiPublicDeviceVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAddonsRoute: typeof AuthenticatedAdminAddonsRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminDeliveryRoute: typeof AuthenticatedAdminDeliveryRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminClientsBusinessIdRoute: typeof AuthenticatedAdminClientsBusinessIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAddonsRoute: AuthenticatedAdminAddonsRoute,
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminDeliveryRoute: AuthenticatedAdminDeliveryRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
  AuthenticatedAdminClientsBusinessIdRoute:
    AuthenticatedAdminClientsBusinessIdRoute,
  AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedStatementMonthRoute: typeof AuthenticatedStatementMonthRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedStatementMonthRoute: AuthenticatedStatementMonthRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AddonsRoute: AddonsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PlatformRoute: PlatformRoute,
  PortalRoute: PortalRoute,
  PricingRoute: PricingRoute,
  ProofRoute: ProofRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialistsRoute: SpecialistsRoute,
  VerifyDeviceRoute: VerifyDeviceRoute,
  ApiPublicCronApplyPlanChangesRoute: ApiPublicCronApplyPlanChangesRoute,
  ApiPublicCronBookingRemindersRoute: ApiPublicCronBookingRemindersRoute,
  ApiPublicCronExpireBusinessesRoute: ApiPublicCronExpireBusinessesRoute,
  ApiPublicCronMonthlyStatementsRoute: ApiPublicCronMonthlyStatementsRoute,
  ApiPublicCronReviewRequestsRoute: ApiPublicCronReviewRequestsRoute,
  ApiPublicDeviceStartRoute: ApiPublicDeviceStartRoute,
  ApiPublicDeviceVerifyRoute: ApiPublicDeviceVerifyRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
